---
abstract: 'SeeAlso Linkserver Protocol Server'
author:
  - 'Jakob Voss'
build_requires:
  CHI: 0
  Cache::Memory: 0
  Data::Dumper: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SeeAlso-Server
requires:
  Business::ISBN: 0
  CGI: 0
  Carp: 0
  Config::IniFiles: 0
  DBI: 0
  DBI::Const::GetInfoType: 0
  Data::Validate::URI: 0
  Date::Parse: 0
  Exporter: 0
  JSON::XS: 0
  LWP::Simple: 0
  POSIX: 0
  Text::CSV: 0
  URI: 0
  YAML::Any: 0
  base: 0
  overload: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gbv/SeeAlso
  repository: https://github.com/gbv/
version: 0.71
