--- #YAML:1.0
name:                SeeAlso-Server
version:             0.55
abstract:            SeeAlso Linkserver Protocol Server
license:             ~
author:              
    - Jakob Voss <jakob.voss@gbv.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Business::ISBN:                2.02
    Carp:                          1.01
    CGI:                           3.0
    Date::Parse:                   2.27
    DBI:                           1.54
    JSON::XS:                      2.0
    URI:                           1.35
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
