# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SeeAlso-Server
version:      0.48
version_from: lib/SeeAlso/Server.pm
installdirs:  site
requires:
    Business::ISBN:                2.02
    Carp:                          1.01
    CGI:                           3.0
    DBI:                           1.54
    JSON:                          2.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
